### ISSUE TITLE
QA_Cryptography_Progress page_Unwanted text and symbols

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/cryptography-iiith#33]
**Defect Description**:
In the Progress page of "Cryptography Lab",  unwanted text and symbols are present. Where as the unwanted text should not be present near the link.

**Actual Result**
In the Progress page of "Cryptography Lab",  unwanted text and symbols are present.

**Environment:**
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment:**
![qa_crypt_i12](https://cloud.githubusercontent.com/assets/13479177/19926152/d4685048-a114-11e6-9dc2-35c57a0b4b0c.png)

**Comment by sravanthimodepu** [comment]
Keeping this issue on hold, as the system's team will look into this.
