### ISSUE TITLE
QA_Cryptography_All Experiments_Simulation issues at open edx

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/cryptography-iiith#34]
Defect Description :
While testing this lab, found that all the experiments are not working. For all the experiments we are assigning the vlabs simualtion link, as all the content of the lab is in one html file it is displaying the whole lab in the experiment section. Instead expeiment link should redirect to the experiment page.

Actual Result :
While testing this lab, found that the simulation is not working. Experiment link should redirect to the experiment page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sravanthimodepu** [comment]
As the simulation is written with php inside the content page, we cannot separate the experiment from the content. Hence keeping the issue on hold.
