### ISSUE TITLE
cryptography-lab_pre-requsite-softwares

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/cryptography-iiith#57]
Defect description: linkage broken. pre requisite courses button are not working.![screenshot__65_](https://gitlab.com/prem_/virtual-labs-internship-prem/uploads/9e3ee639e44b61887d6ed4b00fcd82a1/Screenshot__65_.png)

**Comment by kurasaiteja** [comment]
Invalid Issue.These are not buttons
