### ISSUE TITLE
cryptography lab_breaking the shift cipher"

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/cryptography-iiith#60]
Defect description: the html page design is not goodstep1. first i have logged in to gitlabstep2. next i have opened the virtual labsstep3. i have selected the cryptography labstep4. i opened experiments page, found the content design at the bottom and on the top there is blank spaceexpected result : it should show experiment introduction in the topActual result : first it appeared blank space and then at bottom information was foundscreenshot:![screenshot__36_](https://gitlab.com/jyothsnasheela/virtual-labs-internship-jyothsna/uploads/1e1d71375fbba933464d030ad92b2faf/Screenshot__36_.png)

**Comment by aakarsh7599** [comment]
Fixed in the updated UI
