### ISSUE TITLE
Cryptography_page-bottom-links

### ISSUE THREAD

**Issue by Rashmi-G** [virtual-labs/cryptography-iiith#63]
# Defect description: 
link not found error or no link to be shown in the html form. 
# actual result
1. click on "spansored by MHRD" content link under cryptographylab.
2. the content links to a not found page showing error.
# expected result: 
no link is to be displayed or if correct link is existing then it should be linked in the <"a"> tag of the html page.
screenshot: 
![image](https://user-images.githubusercontent.com/39985156/41996729-6c87c1c2-7a73-11e8-9f60-7e60d0ab5a5d.png)

**Comment by Rashmi-G** [comment]
commit link: e33dfa9f4e02fe01085068c7baba8385fb1a22db

**Comment by kurasaiteja** [comment]
@Rashmi-G the ui is being changed so this link will not be present in the new ui.

**Comment by Rashmi-G** [comment]
@kurasaiteja ok. thankyou.
